language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: false
install:
- mvn --version
before_script:
- export DISPLAY=:99
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- mvn clean install
- cd ..
- mvn clean verify site -U -B -fae